### ISSUE TITLE
Add JS templating system

### ISSUE THREAD

**Issue by alechewitt** [code-wall/codebin#36]
Add moustache templating system

**Comment by alechewitt** [comment]
This, is still work in progress I have temporarily added the handlebars stuff in. However I think we should think about using some kind of framework to give the project more structure and a pattern to follow.

**Comment by Daio-io** [comment]
I guess if we are going to do this my choice would be either React or Backbone. My only concern is adding unwanted bloat for our app when its quite simple in terms of interaction. Is there no clean way to wrap up ui elements in separate classes and get them to render the views on some kind of init?

**Comment by Daio-io** [comment]
Marked with won't fix and closing since we are moving to React
