### ISSUE TITLE
Detect platform and show cmd / ctrl for shortcuts

### ISSUE THREAD

**Issue by Daio-io** [code-wall/codebin#38]
- When browsing to codebin from a Mac it should show the shortcuts as "cmd +" in the keyboard shortcuts modal
- Likewise for all other platforms it should show as "ctrl +" 
- Mobile / tablet should hide any shortcuts

**Comment by alechewitt** [comment]
Yep I think this is a fairly straightforward thing to do and will improve the user experience.

**Comment by alechewitt** [comment]
this is on pull request #52
